name: es-mame-bundle
version: '0.1'
summary: EmulationStation with MAME bundle
description: |
  This package contains EmulationStation with MAME for easy deployment and execution.

grade: stable
confinement: strict
base: core18
type: app

parts:
  emulationstation:
    plugin: cmake
    source: https://github.com/RetroPie/EmulationStation.git
    build-packages:
      - build-essential
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libboost-all-dev
      - libfreetype6-dev
      - libfreeimage-dev
      - libcurl4-gnutls-dev
      - libvlc-dev
      - rapidjson-dev
    stage-packages:
      - libgl1-mesa-glx
      - libglu1-mesa
      - libboost-system1.65.1
      - libboost-filesystem1.65.1
      - libboost-date-time1.65.1
      - libboost-locale1.65.1
      - libfreetype6
      - libfreeimage3
      - libcurl3-gnutls
      - libvlc5
      - libvlccore9
  mame:
    plugin: make
    source: https://github.com/mamedev/mame.git
    build-packages:
      - g++
      - libsdl2-ttf-dev
      - python3
    stage-packages:
      - libsdl2-2.0-0

apps:
  emulationstation:
    command: bin/emulationstation
  mame:
    command: bin/mame
